### ISSUE TITLE
fiberassign tile file extension name has changed

### ISSUE THREAD

**Issue by weaverba137** [sbailey/desitest#12]
The tile files generated by fiberassign used to have an extension called 'FIBER_ASSIGNMENTS', now it appears that has changed to 'FIBERASSIGN'.  Was this intentional?  The change in extension name is preventing loading of the redshift database.

**Comment by weaverba137** [comment]
PS, the data model still says that the extension name should be `FIBER_ASSIGNMENTS`.

**Comment by forero** [comment]
It is intentional. We added new extensions (https://github.com/desihub/fiberassign/pull/119) without updating the data model
