### ISSUE TITLE
choose tiles which span N/S photometric split

### ISSUE THREAD

**Issue by moustakas** [sbailey/desitest#22]
Related to https://github.com/desihub/desispec/issues/680, we now have the ability to simulate targets with `PHOTSYS='S'` vs `PHOTSYS='N'` (see https://github.com/desihub/desitarget/pull/368). 

The tiles used by the minitest.ipynb notebook should span the N/S split so we are explicitly testing our ability to handle these different regions.

**Comment by sbailey** [comment]
The minitest already uses tiles whose centers are between 30 < dec < 35, and thus cover your PHOTSYS N/S boundary at dec=32.125.  I don't recall if this was great foresight when I selected those tiles, or just dumb luck.
