### ISSUE TITLE
Location of lya_forest mocks has changed

### ISSUE THREAD

**Issue by weaverba137** [sbailey/desitest#4]
I'm trying to run the minitest notebook using (mostly) release 18.3, and the `select_mock_targets` stage failed.  Digging into the log files, I found this:

`./53/5352/build-64-5352.log:WARNING:mockmaker.py:1088:readmock: Mock file /project/projectdirs/desi/mocks/lya_forest/v2.0.2/master.fits not found!`

Apparently the arrangement of the lya_forest directory was changed at some point, and not in a backward-compatible way.

I'm using the version of desitarget from release 18.3, 0.20.1.

**Comment by moustakas** [comment]
It looks like a bunch of subdirectories (develop, london, saclay, uncorr) were added by @andreufont the past couple days.

**Comment by julienguy** [comment]
Yes. The mocks were moved. I have just created a symbolic link to fix that
```/project/projectdirs/desi/mocks/lya_forest> ln -fs london/v0.2 v2.0.2```

**Comment by weaverba137** [comment]
@julienguy, thank you!

**Comment by andreufont** [comment]
This should be a more stable structure, at least for a while. Sorry for
lack of communication, I wasn't aware that this would break any test.

Cheers,
Andreu

**Comment by weaverba137** [comment]
OK, let's keep this open until we've confirmed that the test notebook(s) can work with the new layout.

**Comment by weaverba137** [comment]
For the record, I was able to complete a test with the *symlinks*  installed, but I don't think anyone has run the test(s) using the new layout *explicitly*.

**Comment by weaverba137** [comment]
@sbailey agrees it is sufficient that the test notebook passes with just the symlink.
