### ISSUE TITLE
nightly update keep main world readable

### ISSUE THREAD

**Issue by sbailey** [sbailey/desitest#45]
When performing the nightly git pull update of the main branch, run `chmod -R a+rX` or equivalent to ensure world readability (git might reset it back to user+group only based upon the umask)

**Comment by sbailey** [comment]
@marcelo-alvarez I'm reopening this ticket because PR #48 didn't fully fix it.  There are several actions that happen after the each git pull that can generate world non-readable files, e.g. the `python -m compileall ...` steps and the `python setup.py build_ext --inplace` steps of fiberassign and specex.

It looks like the fix needs to be to run `chmod -R a+rX .` per repo after all other steps are done instead of bundling it with the `git pull` step.

From @weaverba137, a command for identifying non-worldreadable files:
```
cd /global/common/software/desi/perlmutter/desiconda
find . -wholename \*/main/\* -not -perm /o+r -ls
```

**Comment by sbailey** [comment]
@marcelo-alvarez the latest PR #49 still didn't fix it.  There are __pycache__ files dated June 12 3:12am that aren't world readable from last night's update.  I will manually re-grant world read to those.  When you are back, please investigate why desitest isn't automatically making these world readable, including explicitly running the desitest scronjob and re-investigating the directory tree with
```
cd /global/common/software/desi/perlmutter/desiconda
find . -wholename \*/main/\* -not -perm /o+r -ls
```

**Comment by marcelo-alvarez** [comment]
@sbailey sorry, I missed that the commands to check it worked were inteded for me to use and not Ben. I am implementing a more robust solution that sets world read access in the script instead of desitest. I will post here once I've explicitly run the desitest scronjob and re-investigated the directory tree with the commands above.

**Comment by marcelo-alvarez** [comment]
@sbailey I have verified that the addition of the lines
```
droot=$DESICONDA/../../
for main in $(find $droot -name main -type d)
do
    chmod -R a+rX $main
done
```
near the end of
```
/global/common/software/desi/users/desi/perlmutter/code/desitest/main/etc/cron_dailyupdate.sh
```
to ensure all "main" source files world readable has worked, by setting the daily update scron job to run early and verifying after its completion that
```
cd /global/common/software/desi/perlmutter/desiconda
find . -wholename \*/main/\* -not -perm /o+r -ls
```
does not return any files or directories. 

Closing now.
