### ISSUE TITLE
KeyError in select_mock_targets stage

### ISSUE THREAD

**Issue by weaverba137** [sbailey/desitest#7]
When running the minitest notebook yesterday, the `select_mock_targets` stage reported errors like this in `/global/cscratch1/sd/bweaver/desi/dev/end2end/targets/select_mock_targets.log`.  Is this related to #6?

```
    targets['MWS_TARGET'] |= (mws_main_very_faint != 0) * self.mws_mask.mask('MWS_MAIN_VERY_FAINT')
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/desiutil/1.9.11/lib/python3.6/site-packages/desiutil-1.9.11-py3.6.egg/desiutil/bitmask.py", line 215, in mask
    mask |= self._bits[name].mask
KeyError: 'MWS_MAIN_VERY_FAINT'
```

**Comment by moustakas** [comment]
This targeting bit was actually dropped in https://github.com/desihub/desitarget/pull/324 but fixed in https://github.com/desihub/desitarget/pull/331, which I think I'm going to go ahead and merge.

**Comment by moustakas** [comment]
OK, using the master branch of desitarget should resolve this issue.

**Comment by weaverba137** [comment]
I'll close now & reopen if there are still problems.

**Comment by weaverba137** [comment]
Well, I just ran the test with both the updated configuration file from #6, *and* with the latest desitarget/master (you can see the path in the traceback below), but got the same error.
```
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/des
itarget/master/py/desitarget/mock/build.py", line 202, in _get_spectra_onepixel
    return get_spectra_onepixel(*specargs)
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/des
itarget/master/py/desitarget/mock/build.py", line 281, in get_spectra_onepixel
    MakeMock.select_targets(chunktargets, chunktruth, boss_std=boss_std)
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/des
itarget/master/py/desitarget/mock/mockmaker.py", line 3234, in select_targets
    targets['MWS_TARGET'] |= (mws_main_very_faint != 0) * self.mws_mask.mask('MW
S_MAIN_VERY_FAINT')
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/des
iutil/1.9.11/lib/python3.6/site-packages/desiutil-1.9.11-py3.6.egg/desiutil/bitm
ask.py", line 215, in mask
    mask |= self._bits[name].mask
KeyError: 'MWS_MAIN_VERY_FAINT'
```

**Comment by moustakas** [comment]
I don't think that's the master branch of desitarget.  Line 3234 looks like this --
  https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/mockmaker.py#L3234

And indeed that module doesn't have the string "MWS_MAIN_VERY_FAINT" anywhere...

**Comment by weaverba137** [comment]
Very weird.  I'll try again.  Maybe something was cached.

**Comment by weaverba137** [comment]
OK, this time it worked.
