### ISSUE TITLE
fiberassign stage fails to read fiberpos_fits_file

### ISSUE THREAD

**Issue by weaverba137** [sbailey/desitest#9]
The fiberassign phase of the minitest notebook fails with this traceback.  Is the variable `fiberpos_fits_file` *actually* a FITS file, with extension `.fits`?
```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/fib
erassign/master/bin/fiberassign", line 104, in <module>
    tmp_fiber_pos = rewrite_fiberpos(args.positioners)
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/fib
erassign/master/bin/fiberassign", line 96, in rewrite_fiberpos
    data = Table.read(fiberpos_fits_file)
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/conda/li
b/python3.6/site-packages/astropy/table/table.py", line 2519, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/conda/li
b/python3.6/site-packages/astropy/io/registry.py", line 528, in read
    'read', cls, path, fileobj, args, kwargs)
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/conda/li
b/python3.6/site-packages/astropy/io/registry.py", line 616, in _get_valid_forma
t
    "{0}".format(format_table_str))
astropy.io.registry.IORegistryError: Format could not be identified.
```

**Comment by weaverba137** [comment]
In fact `args.positioners = /global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/desimodel/0.9.5/data/focalplane/fiberpos.txt` which doesn't look much like a FITS file.

**Comment by weaverba137** [comment]
There is also `dark-tiles.txt` and `bright-tiles.txt`.  Should those also be FITS files?

**Comment by weaverba137** [comment]
Changing `fiberpos.txt` to `fiberpos.fits` seems to have made the Python wrapper `fiberassign` happy, but no tile files were created, and there are no obvious errors in the logs.

**Comment by weaverba137** [comment]
O wow, the Python wrapper uses `os.system()` to call the C++ executable!  That means it doesn't even *try* to report the exit status or anything else back to the caller.  The Python wrapper exits successfully no matter what happens, because it never sets `sys.exit()`.

**Comment by weaverba137** [comment]
I think there are serious problems with the current Python wrapper.  I was able to run the `fiberassign_exec` successfully and generate tile files.  So it looks like the wrapper is failing to copy tile files from the temporary directory it assigns back to the output directory.

**Comment by weaverba137** [comment]
Well, more bad news.  The *first* run of `fiberassign_exec` with `--mtl = mtl.fits` worked, but the *second* run with `--mtl = sky.fits` core dumped.

**Comment by tskisner** [comment]
Independent of whether the wrapper should call subprocess.check_call inside a try / except block (it really should), can you tell me the command line that caused fiberassign_exec to crash?  Is that "sky.fits" somewhere I can grab?  I can try to reproduce it at NERSC.

**Comment by weaverba137** [comment]
Log file is at `/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/fiberassign.log`.  The specific command that failed is:
```
fiberassign_exec --mtl /global/cscratch1/sd/bweaver/desi/dev/end2end/targets/sky.fits  --sky /global/cscratch1/sd/bweaver/desi/dev/end2end/targets/sky.fits --stdstar /global/cscratch1/sd/bweaver/desi/dev/end2end/targets/sky.fits  --fibstatusfile /global/u2/b/bweaver/Documents/Code/git/desihub/desitest/mini/fiberstatus.ecsv              --outdir /tmp/tmpyac4joh0             --surveytiles /global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/dark-tiles.txt              --footprint /global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/desimodel/0.9.5/data/footprint/desi-tiles.fits              --positioners /global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tmp_ETC_pos.txt             --starmask 60129542144             --rundate 2018-06-29
```

**Comment by weaverba137** [comment]
PS, this is using the test-release environment on cori.

**Comment by tskisner** [comment]
I ran this in GDB, and it is crashing in read_fiber_positions().  I'm investigating.

**Comment by tskisner** [comment]
Hmmm, looks like the "/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tmp_ETC_pos.txt" no longer exists (is that created by the wrapper)?  That was the reason my test failed.

Looks like the wrapper is reading a FITS file, creating a temporary TXT file, and then reading that in C++?

**Comment by weaverba137** [comment]
That is my interpretation of what the wrapper does.  I thought I left those temporary files in place though.  Let me take a look.

**Comment by weaverba137** [comment]
The temporary files are still there, and readable by group desi.

**Comment by sbailey** [comment]
Mentioning @forero to get him in the loop on this too, since he wrote the original python wrapper to call `fiberassign_exec`.

**Comment by sbailey** [comment]
@tskisner and @forero any updates on this?

**Comment by tskisner** [comment]
Sorry I dropped this- perhaps a good start would be to have the full commandline to the fiberassign wrapper that failed.  Then I can go run that myself and not worry about trying to read temp files created by another person.

Longer term, the wrapper should at least use subprocess to run fiberassign_exec.  If reading FITS from C/C++ is just too much for people, then perhaps we could move fiberassign into a library that we call with ctypes (like specex).  Or we could use other techniques (pybind11, etc).

**Comment by sbailey** [comment]
Try this for reproducing the failure:
```
fiberassign  \
--mtl /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/mtl.fits \
--stdstar /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/standards-dark.fits \
--sky /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/sky.fits \
--surveytiles /global/cscratch1/sd/sjbailey/desi/dev/end2end/fiberassign/dark-tiles.txt \
--footprint /global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desimodel/master/data/footprint/desi-tiles.fits \
--positioners /global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desimodel/master/data/focalplane/fiberpos.txt \
--fibstatusfile /global/cscratch1/sd/sjbailey/desi/code/desitest/mini/fiberstatus.ecsv \
--outdir $SCRATCH/temp/
```

**Comment by forero** [comment]
For `fiberassign` --positioners must be a fits file; for `fiberassign_exec` it must be a text file.

**Comment by sbailey** [comment]
Ah ha!  It also must be the `fiberpos-all.fits` file (which includes the location of the sky monitor "ETC" fibers in addition to the normal "POS" positioners) not just the `fiberpos.fits` file.  I've updated desihub/fiberassign#113 (robustness to input format errors) with this example.

@weaverba137: solution for the minitest notebook is to either drop the `--positioners` argument since it will default to `$DESIMODEL/data/focalplane/fiberpos-all.fits` anyway, or to explicitly set it to that file (and not `fiberpos.txt` nor `fiberpos.fits`).  I'd probably prefer to just drop the argument to simplify the command line script that is called.  You could also drop the `--footprint` option since that also now has a reasonable default.

I've confirmed that that works outside of the context of the minitest notebook.  @weaverba137 please confirm that it does work within the notebook and that you can proceed beyond that state.  If yes, then you can close this; if not, then please report any new problems here.

**Comment by weaverba137** [comment]
Hmm, looks like cori is *still* down, or at least the notebook service is.

**Comment by weaverba137** [comment]
@sbailey, I was able to get past the fiberassign stage in the minitest notebook this morning.  `is_fiberassign_done()` indicated success, but because the `fiberassign` Python script doesn't return a meaningful exit code, one can't be sure.  Here is the output of `qa-fiberassign`.   I'm not entirely sure what the nominal output is supposed to be.
```
Total SKY fibers 400
Total STDSTAR fibers 0
/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tile_01165.fits - ERROR
  5 unassigned fibers
  Petal 0 has 0/10 stdstars
  Petal 1 has 0/10 stdstars
  Petal 2 has 0/10 stdstars
  Petal 3 has 0/10 stdstars
  Petal 4 has 0/10 stdstars
  Petal 5 has 0/10 stdstars
  Petal 6 has 0/10 stdstars
  Petal 7 has 0/10 stdstars
  Petal 8 has 0/10 stdstars
  Petal 9 has 0/10 stdstars
0 stuck fibers
0 broken fibers
Total SKY fibers 400
Total STDSTAR fibers 0
/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tile_06927.fits - ERROR
  5 unassigned fibers
  Petal 0 has 0/10 stdstars
  Petal 1 has 0/10 stdstars
  Petal 2 has 0/10 stdstars
  Petal 3 has 0/10 stdstars
  Petal 4 has 0/10 stdstars
  Petal 5 has 0/10 stdstars
  Petal 6 has 0/10 stdstars
  Petal 7 has 0/10 stdstars
  Petal 8 has 0/10 stdstars
  Petal 9 has 0/10 stdstars
0 stuck fibers
0 broken fibers
Total SKY fibers 400
Total STDSTAR fibers 0
/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tile_11108.fits - ERROR
  5 unassigned fibers
  Petal 0 has 0/10 stdstars
  Petal 1 has 0/10 stdstars
  Petal 2 has 0/10 stdstars
  Petal 3 has 0/10 stdstars
  Petal 4 has 0/10 stdstars
  Petal 5 has 0/10 stdstars
  Petal 6 has 0/10 stdstars
  Petal 7 has 0/10 stdstars
  Petal 8 has 0/10 stdstars
  Petal 9 has 0/10 stdstars
0 stuck fibers
0 broken fibers
Total SKY fibers 400
Total STDSTAR fibers 0
/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tile_16870.fits - ERROR
  5 unassigned fibers
  Petal 0 has 0/10 stdstars
  Petal 1 has 0/10 stdstars
  Petal 2 has 0/10 stdstars
  Petal 3 has 0/10 stdstars
  Petal 4 has 0/10 stdstars
  Petal 5 has 0/10 stdstars
  Petal 6 has 0/10 stdstars
  Petal 7 has 0/10 stdstars
  Petal 8 has 0/10 stdstars
  Petal 9 has 0/10 stdstars
0 stuck fibers
0 broken fibers
Total SKY fibers 400
Total STDSTAR fibers 0
/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tile_18465.fits - ERROR
  6 unassigned fibers
  Petal 0 has 0/10 stdstars
  Petal 1 has 0/10 stdstars
  Petal 2 has 0/10 stdstars
  Petal 3 has 0/10 stdstars
  Petal 4 has 0/10 stdstars
  Petal 5 has 0/10 stdstars
  Petal 6 has 0/10 stdstars
  Petal 7 has 0/10 stdstars
  Petal 8 has 0/10 stdstars
  Petal 9 has 0/10 stdstars
0 stuck fibers
0 broken fibers
Total SKY fibers 400
Total STDSTAR fibers 0
/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tile_24227.fits - ERROR
  5 unassigned fibers
  Petal 0 has 0/10 stdstars
  Petal 1 has 0/10 stdstars
  Petal 2 has 0/10 stdstars
  Petal 3 has 0/10 stdstars
  Petal 4 has 0/10 stdstars
  Petal 5 has 0/10 stdstars
  Petal 6 has 0/10 stdstars
  Petal 7 has 0/10 stdstars
  Petal 8 has 0/10 stdstars
  Petal 9 has 0/10 stdstars
0 stuck fibers
0 broken fibers
Total SKY fibers 400
Total STDSTAR fibers 0
/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tile_28408.fits - ERROR
  5 unassigned fibers
  Petal 0 has 0/10 stdstars
  Petal 1 has 0/10 stdstars
  Petal 2 has 0/10 stdstars
  Petal 3 has 0/10 stdstars
  Petal 4 has 0/10 stdstars
  Petal 5 has 0/10 stdstars
  Petal 6 has 0/10 stdstars
  Petal 7 has 0/10 stdstars
  Petal 8 has 0/10 stdstars
  Petal 9 has 0/10 stdstars
0 stuck fibers
0 broken fibers
Total SKY fibers 400
Total STDSTAR fibers 4
/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tile_34170.fits - ERROR
  13 unassigned fibers
  Petal 0 has 0/10 stdstars
  Petal 1 has 1/10 stdstars
  Petal 2 has 0/10 stdstars
  Petal 3 has 0/10 stdstars
  Petal 4 has 1/10 stdstars
  Petal 5 has 2/10 stdstars
  Petal 6 has 0/10 stdstars
  Petal 7 has 0/10 stdstars
  Petal 8 has 0/10 stdstars
  Petal 9 has 0/10 stdstars
0 stuck fibers
0 broken fibers
Total SKY fibers 400
Total STDSTAR fibers 1
/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tile_39942.fits - ERROR
  5 unassigned fibers
  Petal 0 has 0/10 stdstars
  Petal 1 has 0/10 stdstars
  Petal 2 has 0/10 stdstars
  Petal 3 has 0/10 stdstars
  Petal 4 has 0/10 stdstars
  Petal 5 has 0/10 stdstars
  Petal 6 has 0/10 stdstars
  Petal 7 has 0/10 stdstars
  Petal 8 has 0/10 stdstars
  Petal 9 has 1/10 stdstars
0 stuck fibers
0 broken fibers
Total SKY fibers 400
Total STDSTAR fibers 17
/global/cscratch1/sd/bweaver/desi/dev/end2end/fiberassign/tile_45704.fits - ERROR
  6 unassigned fibers
  Petal 0 has 2/10 stdstars
  Petal 1 has 5/10 stdstars
  Petal 2 has 1/10 stdstars
  Petal 3 has 2/10 stdstars
  Petal 4 has 3/10 stdstars
  Petal 5 has 1/10 stdstars
  Petal 6 has 1/10 stdstars
  Petal 7 has 0/10 stdstars
  Petal 8 has 1/10 stdstars
  Petal 9 has 1/10 stdstars
0 stuck fibers
0 broken fibers
10/10 tiles had errors
----------
56.1% targets (129340/230516) covered by 10 tiles
  Dropping 101176 targets not covered by any tile:fiber
Fiber assignment efficiency
  ELG       37.0%  (17937/48429)
  LRG       72.8%  (5841/8025)
  QSO       94.3%  (3451/3661)
  MWS_ANY    1.9%  (514/27165)
  BGS_ANY   32.5%  (13656/42061)

---------------------------------------------------------------
WORK IN PROGRESS
The stats below mix dark/bright/gray without considering that a
dark target can't be observed on a bright tile
---------------------------------------------------------------

Percent of targets covered exactly N times
            1     2     3     4     5     6     7     8     9
          33.7  26.9  17.9  11.4   4.9   3.8   1.1   0.3   0.0

Percent of targets covered at least N times
            1     2     3     4     5     6     7     8     9
         100.0  66.3  39.4  21.5  10.1   5.2   1.4   0.3   0.0

Assignment probability if covered exactly N times
            1     2     3     4     5     6     7     8     9
ELG       18.3  34.0  48.1  61.2  73.1  81.9   ---   ---   ---
LRG       60.2  80.2  86.4  88.1  98.6   ---   ---   ---   ---
QSO       87.4  99.2 100.0 100.0 100.0   ---   ---   ---   ---
MWS_ANY    0.0   0.5   0.8   1.6   4.9   8.2   6.4  10.7   ---
BGS_ANY   31.9  36.7  27.4  18.7  33.4  46.2  49.1  49.3   ---
```

**Comment by sbailey** [comment]
Something is wrong in that the dark tiles have 0 standard stars, and the bright tiles have just a few.  Check that the input `targets/standards-dark.fits` and `targets/standards-bright.fits` actually have targets in them, and that they have DESI_TARGET bits 33, 34, and/or 35 set (see [targetmask.yaml](https://github.com/desihub/desitarget/blob/master/py/desitarget/data/targetmask.yaml)), and that those are the bits that fiberassign is expecting to use for standard stars.

**Comment by weaverba137** [comment]
`targets/standards-dark.fits` has 1217 rows, `targets/standards-bright.fits` has 540 rows.  Digging into the bit values now.

**Comment by weaverba137** [comment]
The standards files pass the following test:
```python
for program in ('dark', 'bright'):
    std = os.path.join(targetdir, 'standards-{0}.fits'.format(program))
    with fits.open(std) as hdulist:
        desi_target = hdulist[1].data['DESI_TARGET']
    assert ((np.bitwise_and(desi_target, 2**33) != 0) |
            (np.bitwise_and(desi_target, 2**34) != 0) |
            (np.bitwise_and(desi_target, 2**35) != 0)).all()
```

**Comment by weaverba137** [comment]
As far as I can tell the `fiberassign` script is passing the standard star file names to the executable correctly.

**Comment by weaverba137** [comment]
The fiberassign log doesn't show any obvious error messages, although with the Python script are we certain that we are capturing both stdout & stderr from the executable?

**Comment by sbailey** [comment]
Running fiberassign by hand:
```
fiberassign  --mtl /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/mtl.fits --stdstar /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/standards-dark.fits --sky /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/sky.fits --surveytiles /global/cscratch1/sd/sjbailey/desi/dev/end2end/fiberassign/dark-tiles.txt --footprint /global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desimodel/master/data/footprint/desi-tiles.fits --positioners /global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desimodel/master/data/focalplane/fiberpos-all.fits --fibstatusfile /global/cscratch1/sd/sjbailey/desi/code/desitest/mini/fiberstatus.ecsv --outdir $SCRATCH/temp/
```
I see this in the log:
```
...
Keeping 48128 targets within ra/dec ranges
# ...read targets  took : 0.123 s
 Target size 48128 
 Standard Star size 48128 
 Sky Fiber size 96256 
...
# assign SS and SF  at 0.452 s
# count SS and SF  at 0.452 s
 Totals SS      0    SF      0 class  0       0
```
SS = standard star and SF = sky fiber; it appears that they are read in correctly but are getting dropped along the way before they are assigned.

**Comment by weaverba137** [comment]
Are you sure those messages are from the same call to the *executable*?

**Comment by sbailey** [comment]
Ah, indeed.  The executable does get called twice, one for the main fibers and once for the sky monitor fibers and I was mixing logs.  For the first call on the science positioners:
```
 Totals SS      0    SF   2800 class  0       0 class  1      13 class  2       0 class  3     549 class  4       0 class  5   17789 class  6    8013 class  7    5797
```
So SS is still 0, but I don't know why...

**Comment by weaverba137** [comment]
The only thing I can think of is to try running the executable by hand to see if any additional information is printed to stderr and not captured by the Python script.

**Comment by weaverba137** [comment]
I don't think we're missing anything on stderr at this point.  Whatever is dropping the standard stars is happening deep within the C++ code.

**Comment by sbailey** [comment]
I spun this off to desihub/fiberassign#130 since it appears to be a genuine problem with fiberassign, not with how the test is calling fiberassign.

**Comment by rncahn** [comment]
I've been working on resurrecting quicksurvey using my own branches based
on old versions of fiberassign and desisim.

If I clone the current master versions of those, I suppose I should be able
to reproduce your issue, right?

**Comment by weaverba137** [comment]
@rncahn, correct, this problem is on the master branch.

**Comment by forero** [comment]
@weaverba137 Indeed. There was a bug in fiberassign. I am discussing the fix here https://github.com/desihub/fiberassign/issues/130

**Comment by weaverba137** [comment]
I ran the notebook with this fix implemented, and standard stars were allocated.
